// Paste the code generated by Admin Panel here
const newsDatabase = [
    {
        id: "post1",
        type: "block", // 'block' or 'shop'
        title: "Private Base Breach Raises Questions Across Eldoriaaa Server",
        author: "VGAMER56588",
        date: "Dec 27, 2025",
        image: "https://media.discordapp.net/attachments/1186863316660916329/1454419551596056728/2025-12-26_23.38.14.png?ex=69510542&is=694fb3c2&hm=30fc4b32dddc22bbebfbf4e1aa535147ac8ea76bcf885d7b6ee1a86c089fefe8&=&format=webp&quality=lossless&width=1194&height=615",
        link: "dailyblocknews/post1.html" // The file you saved
    },
    // If you delete everything inside these brackets [], it will show "None"
];

// Do not edit below this line
window.eldoriaDB = newsDatabase;
