// Paste the code generated by Admin Panel here
const newsDatabase = [
    {
        id: "post1",
        type: "block", // 'block' or 'shop'
        title: "Private Base Breach Raises Questions Across Eldoriaaa Server",
        author: "VGAMER56588",
        date: "Dec 27, 2025",
        image: "https://placehold.co/600x300/111/00ff88?text=DRAGON",
        link: "dailyblocknews/post1.html" // The file you saved
    },
    // If you delete everything inside these brackets [], it will show "None"
];

// Do not edit below this line
window.eldoriaDB = newsDatabase;
